/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_dvdplay_aem_NMC */

#ifndef _Included_net_dvdplay_aem_NMC
#define _Included_net_dvdplay_aem_NMC
#ifdef __cplusplus
extern "C" {
#endif
#undef net_dvdplay_aem_NMC_SEND_INPUTS
#define net_dvdplay_aem_NMC_SEND_INPUTS 1L
#undef net_dvdplay_aem_NMC_SEND_POS
#define net_dvdplay_aem_NMC_SEND_POS 1L
#undef net_dvdplay_aem_NMC_SEND_HOME
#define net_dvdplay_aem_NMC_SEND_HOME 16L
#undef net_dvdplay_aem_NMC_LOAD_POS
#define net_dvdplay_aem_NMC_LOAD_POS 1L
#undef net_dvdplay_aem_NMC_LOAD_VEL
#define net_dvdplay_aem_NMC_LOAD_VEL 2L
#undef net_dvdplay_aem_NMC_LOAD_ACC
#define net_dvdplay_aem_NMC_LOAD_ACC 4L
#undef net_dvdplay_aem_NMC_ENABLE_SERVO
#define net_dvdplay_aem_NMC_ENABLE_SERVO 16L
#undef net_dvdplay_aem_NMC_VEL_MODE
#define net_dvdplay_aem_NMC_VEL_MODE 32L
#undef net_dvdplay_aem_NMC_START_NOW
#define net_dvdplay_aem_NMC_START_NOW 128L
#undef net_dvdplay_aem_NMC_ON_LIMIT1
#define net_dvdplay_aem_NMC_ON_LIMIT1 1L
#undef net_dvdplay_aem_NMC_HOME_STOP_SMOOTH
#define net_dvdplay_aem_NMC_HOME_STOP_SMOOTH 32L
#undef net_dvdplay_aem_NMC_AMP_ENABLE
#define net_dvdplay_aem_NMC_AMP_ENABLE 1L
#undef net_dvdplay_aem_NMC_MOTOR_OFF
#define net_dvdplay_aem_NMC_MOTOR_OFF 2L
#undef net_dvdplay_aem_NMC_STOP_ABRUPT
#define net_dvdplay_aem_NMC_STOP_ABRUPT 4L
#undef net_dvdplay_aem_NMC_STOP_SMOOTH
#define net_dvdplay_aem_NMC_STOP_SMOOTH 8L
#undef net_dvdplay_aem_NMC_MOVE_DONE
#define net_dvdplay_aem_NMC_MOVE_DONE 1L
#undef net_dvdplay_aem_NMC_HOME_IN_PROG
#define net_dvdplay_aem_NMC_HOME_IN_PROG 128L
/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    NmcInit
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_NMC_NmcInit
(JNIEnv*, jclass, jstring, jint);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    NmcShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_NMC_NmcShutdown
(JNIEnv*, jclass);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    NmcHardReset
 * Signature: (B)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_NmcHardReset
(JNIEnv*, jclass, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    NmcNoOp
 * Signature: (B)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_NmcNoOp
(JNIEnv*, jclass, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    NmcDefineStatus
 * Signature: (BB)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_NmcDefineStatus
(JNIEnv*, jclass, jbyte, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    NmcReadStatus
 * Signature: (BB)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_NmcReadStatus
(JNIEnv*, jclass, jbyte, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    NmcGetStat
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_NMC_NmcGetStat
(JNIEnv*, jclass, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    ErrorPrinting
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_NMC_ErrorPrinting
(JNIEnv*, jclass, jint);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    SioOpen
 * Signature: (Ljava/lang/String;I)C
 */
JNIEXPORT jchar JNICALL Java_net_dvdplay_aem_NMC_SioOpen
(JNIEnv*, jclass, jstring, jint);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    SioClose
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_SioClose
(JNIEnv*, jclass, jchar);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    SioPutChars
 * Signature: (CLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_SioPutChars
(JNIEnv*, jclass, jchar, jstring, jint);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    SioChangeBaud
 * Signature: (CI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_SioChangeBaud
(JNIEnv*, jclass, jchar, jint);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    SioClrInbuf
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_SioClrInbuf
(JNIEnv*, jclass, jchar);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    IoClrOutBit
 * Signature: (BI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_IoClrOutBit
(JNIEnv*, jclass, jbyte, jint);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    IoBitDirIn
 * Signature: (BI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_IoBitDirIn
(JNIEnv*, jclass, jbyte, jint);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    IoBitDirOut
 * Signature: (BI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_IoBitDirOut
(JNIEnv*, jclass, jbyte, jint);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    IoInBitVal
 * Signature: (BI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_IoInBitVal
(JNIEnv*, jclass, jbyte, jint);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    IoSetOutBit
 * Signature: (BI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_IoSetOutBit
(JNIEnv*, jclass, jbyte, jint);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    IoSetPWMVal
 * Signature: (BBB)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_IoSetPWMVal
(JNIEnv*, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    ServoSetGain
 * Signature: (BIIIIBBIBB)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_ServoSetGain
(JNIEnv*, jclass, jbyte, jint, jint, jint, jint, jbyte, jbyte, jint, jbyte, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    ServoStopMotor
 * Signature: (BB)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_ServoStopMotor
(JNIEnv*, jclass, jbyte, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    ServoLoadTraj
 * Signature: (BBIIIB)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_ServoLoadTraj
(JNIEnv*, jclass, jbyte, jbyte, jint, jint, jint, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    ServoSetHoming
 * Signature: (BB)Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_NMC_ServoSetHoming
(JNIEnv*, jclass, jbyte, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    ServoGetHome
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_NMC_ServoGetHome
(JNIEnv*, jclass, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    ServoGetPos
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_NMC_ServoGetPos
(JNIEnv*, jclass, jbyte);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    getTimeZoneInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_dvdplay_aem_NMC_getTimeZoneInfo
(JNIEnv*, jclass);

/*
 * Class:     net_dvdplay_aem_NMC
 * Method:    setTimeZoneInfo
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_NMC_setTimeZoneInfo
(JNIEnv*, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
