/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_dvdplay_aem_DPEC */

#ifndef _Included_net_dvdplay_aem_DPEC
#define _Included_net_dvdplay_aem_DPEC
#ifdef __cplusplus
extern "C" {
#endif
#undef net_dvdplay_aem_DPEC_MODEL_UNKNOWN
#define net_dvdplay_aem_DPEC_MODEL_UNKNOWN 0L
#undef net_dvdplay_aem_DPEC_MODEL_A100
#define net_dvdplay_aem_DPEC_MODEL_A100 1L
#undef net_dvdplay_aem_DPEC_MODEL_A100P
#define net_dvdplay_aem_DPEC_MODEL_A100P 2L
#undef net_dvdplay_aem_DPEC_MODEL_A350
#define net_dvdplay_aem_DPEC_MODEL_A350 3L
#undef net_dvdplay_aem_DPEC_MODE_UNKNOWN
#define net_dvdplay_aem_DPEC_MODE_UNKNOWN 0L
#undef net_dvdplay_aem_DPEC_MODE_TRANSITION
#define net_dvdplay_aem_DPEC_MODE_TRANSITION 1L
#undef net_dvdplay_aem_DPEC_MODE_OPERATIONAL
#define net_dvdplay_aem_DPEC_MODE_OPERATIONAL 2L
#undef net_dvdplay_aem_DPEC_MODE_DIAGNOSTIC
#define net_dvdplay_aem_DPEC_MODE_DIAGNOSTIC 3L
#undef net_dvdplay_aem_DPEC_SLOTSTAT_UNKNOWN
#define net_dvdplay_aem_DPEC_SLOTSTAT_UNKNOWN 0L
#undef net_dvdplay_aem_DPEC_SLOTSTAT_EMPTY
#define net_dvdplay_aem_DPEC_SLOTSTAT_EMPTY 1L
#undef net_dvdplay_aem_DPEC_SLOTSTAT_FULL
#define net_dvdplay_aem_DPEC_SLOTSTAT_FULL 2L
#undef net_dvdplay_aem_DPEC_SLOTSTAT_BAD
#define net_dvdplay_aem_DPEC_SLOTSTAT_BAD 3L
#undef net_dvdplay_aem_DPEC_OP_NONE
#define net_dvdplay_aem_DPEC_OP_NONE 0L
#undef net_dvdplay_aem_DPEC_OP_NOP_ASYNC
#define net_dvdplay_aem_DPEC_OP_NOP_ASYNC 1L
#undef net_dvdplay_aem_DPEC_OP_NOP_QUICK
#define net_dvdplay_aem_DPEC_OP_NOP_QUICK 2L
#undef net_dvdplay_aem_DPEC_OP_NOP_ROBOT
#define net_dvdplay_aem_DPEC_OP_NOP_ROBOT 3L
#undef net_dvdplay_aem_DPEC_OP_GETTAGGEDINFO
#define net_dvdplay_aem_DPEC_OP_GETTAGGEDINFO 4L
#undef net_dvdplay_aem_DPEC_OP_SETCONTROLQUICK
#define net_dvdplay_aem_DPEC_OP_SETCONTROLQUICK 5L
#undef net_dvdplay_aem_DPEC_OP_GETSTATUSQUICK
#define net_dvdplay_aem_DPEC_OP_GETSTATUSQUICK 6L
#undef net_dvdplay_aem_DPEC_OP_RAPIDSLOTCHECK
#define net_dvdplay_aem_DPEC_OP_RAPIDSLOTCHECK 7L
#undef net_dvdplay_aem_DPEC_OP_ACCEPTCASETOINSPECT
#define net_dvdplay_aem_DPEC_OP_ACCEPTCASETOINSPECT 8L
#undef net_dvdplay_aem_DPEC_OP_EJECTCASEFROMINSPECT
#define net_dvdplay_aem_DPEC_OP_EJECTCASEFROMINSPECT 9L
#undef net_dvdplay_aem_DPEC_OP_PULLCASEINFROMINSPECT
#define net_dvdplay_aem_DPEC_OP_PULLCASEINFROMINSPECT 10L
#undef net_dvdplay_aem_DPEC_OP_PUSHCASEOUTTOINSPECT
#define net_dvdplay_aem_DPEC_OP_PUSHCASEOUTTOINSPECT 11L
#undef net_dvdplay_aem_DPEC_OP_ROTATETOSLOT
#define net_dvdplay_aem_DPEC_OP_ROTATETOSLOT 12L
#undef net_dvdplay_aem_DPEC_OP_PULLCASEINTOSLOT
#define net_dvdplay_aem_DPEC_OP_PULLCASEINTOSLOT 13L
#undef net_dvdplay_aem_DPEC_OP_EJECTCASEFROMSLOT
#define net_dvdplay_aem_DPEC_OP_EJECTCASEFROMSLOT 14L
#undef net_dvdplay_aem_DPEC_OP_PULLCASETOINSPECT
#define net_dvdplay_aem_DPEC_OP_PULLCASETOINSPECT 15L
#undef net_dvdplay_aem_DPEC_OP_PUSHCASEFROMINSPECT
#define net_dvdplay_aem_DPEC_OP_PUSHCASEFROMINSPECT 16L
#undef net_dvdplay_aem_DPEC_OP_MOVEINSPECTTOSLOT
#define net_dvdplay_aem_DPEC_OP_MOVEINSPECTTOSLOT 17L
#undef net_dvdplay_aem_DPEC_OP_MOVESLOTTOINSPECT
#define net_dvdplay_aem_DPEC_OP_MOVESLOTTOINSPECT 18L
#undef net_dvdplay_aem_DPEC_OP_MOVESLOTTOOUTPUT
#define net_dvdplay_aem_DPEC_OP_MOVESLOTTOOUTPUT 19L
#undef net_dvdplay_aem_DPEC_OP_MOVESLOTTOSLOT
#define net_dvdplay_aem_DPEC_OP_MOVESLOTTOSLOT 20L
#undef net_dvdplay_aem_DPEC_OP_CHECKSLOTFORCASE
#define net_dvdplay_aem_DPEC_OP_CHECKSLOTFORCASE 21L
#undef net_dvdplay_aem_DPEC_Op_UPDATEFIRMWARE
#define net_dvdplay_aem_DPEC_Op_UPDATEFIRMWARE 22L
#undef net_dvdplay_aem_DPEC_Op_CALIBRATE
#define net_dvdplay_aem_DPEC_Op_CALIBRATE 23L
#undef net_dvdplay_aem_DPEC_Op_DIAG100P_TBD
#define net_dvdplay_aem_DPEC_Op_DIAG100P_TBD 24L
#undef net_dvdplay_aem_DPEC_Op_DIAG350_TBD
#define net_dvdplay_aem_DPEC_Op_DIAG350_TBD 25L
#undef net_dvdplay_aem_DPEC_CONTROLITEM_NONE
#define net_dvdplay_aem_DPEC_CONTROLITEM_NONE 0L
#undef net_dvdplay_aem_DPEC_CONTROLITEM_MAINMONITOR
#define net_dvdplay_aem_DPEC_CONTROLITEM_MAINMONITOR 1L
#undef net_dvdplay_aem_DPEC_CONTROLITEM_BARCODELIGHT
#define net_dvdplay_aem_DPEC_CONTROLITEM_BARCODELIGHT 2L
#undef net_dvdplay_aem_DPEC_CONTROLITEM_REBOOTHOST
#define net_dvdplay_aem_DPEC_CONTROLITEM_REBOOTHOST 3L
#undef net_dvdplay_aem_DPEC_OFF
#define net_dvdplay_aem_DPEC_OFF 0L
#undef net_dvdplay_aem_DPEC_ON
#define net_dvdplay_aem_DPEC_ON 1L
#undef net_dvdplay_aem_DPEC_NO
#define net_dvdplay_aem_DPEC_NO 0L
#undef net_dvdplay_aem_DPEC_YES
#define net_dvdplay_aem_DPEC_YES 1L
#undef net_dvdplay_aem_DPEC_STATUSITEM_NONE
#define net_dvdplay_aem_DPEC_STATUSITEM_NONE 0L
#undef net_dvdplay_aem_DPEC_STATUSITEM_CASEINENTRY
#define net_dvdplay_aem_DPEC_STATUSITEM_CASEINENTRY 1L
#undef net_dvdplay_aem_DPEC_STATUSITEM_VALIDCASE
#define net_dvdplay_aem_DPEC_STATUSITEM_VALIDCASE 2L
#undef net_dvdplay_aem_DPEC_STATUSITEM_CASEINSLOT
#define net_dvdplay_aem_DPEC_STATUSITEM_CASEINSLOT 3L
#undef net_dvdplay_aem_DPEC_STATUSITEM_INTAMPTEMP
#define net_dvdplay_aem_DPEC_STATUSITEM_INTAMPTEMP 4L
#undef net_dvdplay_aem_DPEC_STATUSITEM_EXTAMPTEMP
#define net_dvdplay_aem_DPEC_STATUSITEM_EXTAMPTEMP 5L
#undef net_dvdplay_aem_DPEC_STATUSITEM_CPUAMPTEMP
#define net_dvdplay_aem_DPEC_STATUSITEM_CPUAMPTEMP 6L
#undef net_dvdplay_aem_DPEC_STATUSITEM_LCDAMPTEMP
#define net_dvdplay_aem_DPEC_STATUSITEM_LCDAMPTEMP 7L
#undef net_dvdplay_aem_DPEC_STATUSITEM_PWRMONSTAT
#define net_dvdplay_aem_DPEC_STATUSITEM_PWRMONSTAT 8L
#undef net_dvdplay_aem_DPEC_STATUSITEM_DOORLOCKED
#define net_dvdplay_aem_DPEC_STATUSITEM_DOORLOCKED 9L
#undef net_dvdplay_aem_DPEC_EVENT_NONE
#define net_dvdplay_aem_DPEC_EVENT_NONE 0L
#undef net_dvdplay_aem_DPEC_EVENT_ENTRYFILLED
#define net_dvdplay_aem_DPEC_EVENT_ENTRYFILLED 1L
#undef net_dvdplay_aem_DPEC_EVENT_ENTRYEMPTY
#define net_dvdplay_aem_DPEC_EVENT_ENTRYEMPTY 2L
#undef net_dvdplay_aem_DPEC_EVENT_VALIDCASE
#define net_dvdplay_aem_DPEC_EVENT_VALIDCASE 3L
#undef net_dvdplay_aem_DPEC_EVENT_NOVALIDCASE
#define net_dvdplay_aem_DPEC_EVENT_NOVALIDCASE 4L
#undef net_dvdplay_aem_DPEC_EVENT_HITEMPALERT
#define net_dvdplay_aem_DPEC_EVENT_HITEMPALERT 5L
#undef net_dvdplay_aem_DPEC_EVENT_LOTEMPALERT
#define net_dvdplay_aem_DPEC_EVENT_LOTEMPALERT 6L
#undef net_dvdplay_aem_DPEC_EVENT_POWERALERT
#define net_dvdplay_aem_DPEC_EVENT_POWERALERT 7L
#undef net_dvdplay_aem_DPEC_EVENT_APPWDTALERT
#define net_dvdplay_aem_DPEC_EVENT_APPWDTALERT 8L
#undef net_dvdplay_aem_DPEC_EVENT_HITEMPFAULT
#define net_dvdplay_aem_DPEC_EVENT_HITEMPFAULT 9L
#undef net_dvdplay_aem_DPEC_EVENT_LOTEMPFAULT
#define net_dvdplay_aem_DPEC_EVENT_LOTEMPFAULT 10L
#undef net_dvdplay_aem_DPEC_EVENT_POWERFAULT
#define net_dvdplay_aem_DPEC_EVENT_POWERFAULT 11L
#undef net_dvdplay_aem_DPEC_EVENT_APPWDTFAULT
#define net_dvdplay_aem_DPEC_EVENT_APPWDTFAULT 12L
#undef net_dvdplay_aem_DPEC_EVENT_INTRUSWOPEN
#define net_dvdplay_aem_DPEC_EVENT_INTRUSWOPEN 13L
#undef net_dvdplay_aem_DPEC_EVENT_INTRUSWCLOSE
#define net_dvdplay_aem_DPEC_EVENT_INTRUSWCLOSE 14L
#undef net_dvdplay_aem_DPEC_RESULT_SUCCESS
#define net_dvdplay_aem_DPEC_RESULT_SUCCESS 0L
#undef net_dvdplay_aem_DPEC_RESULT_FAILED
#define net_dvdplay_aem_DPEC_RESULT_FAILED 1L
#undef net_dvdplay_aem_DPEC_RESULT_ABORTED
#define net_dvdplay_aem_DPEC_RESULT_ABORTED 2L
#undef net_dvdplay_aem_DPEC_RESULT_UNKNOWN
#define net_dvdplay_aem_DPEC_RESULT_UNKNOWN 3L
#undef net_dvdplay_aem_DPEC_RESULT_TIMEOUT
#define net_dvdplay_aem_DPEC_RESULT_TIMEOUT 4L
#undef net_dvdplay_aem_DPEC_RESULT_NOCONNECT
#define net_dvdplay_aem_DPEC_RESULT_NOCONNECT 5L
#undef net_dvdplay_aem_DPEC_RESULT_CONNECTED
#define net_dvdplay_aem_DPEC_RESULT_CONNECTED 6L
#undef net_dvdplay_aem_DPEC_RESULT_NORESOURCE
#define net_dvdplay_aem_DPEC_RESULT_NORESOURCE 7L
#undef net_dvdplay_aem_DPEC_RESULT_CANTCOMPLETE
#define net_dvdplay_aem_DPEC_RESULT_CANTCOMPLETE 8L
#undef net_dvdplay_aem_DPEC_RESULT_SRCEMPTY
#define net_dvdplay_aem_DPEC_RESULT_SRCEMPTY 9L
#undef net_dvdplay_aem_DPEC_RESULT_DSTOCCUPIED
#define net_dvdplay_aem_DPEC_RESULT_DSTOCCUPIED 10L
#undef net_dvdplay_aem_DPEC_RESULT_SLOTEMPTY
#define net_dvdplay_aem_DPEC_RESULT_SLOTEMPTY 11L
#undef net_dvdplay_aem_DPEC_RESULT_SLOTFULL
#define net_dvdplay_aem_DPEC_RESULT_SLOTFULL 12L
#undef net_dvdplay_aem_DPEC_RESULT_BADVALUE
#define net_dvdplay_aem_DPEC_RESULT_BADVALUE 13L
#undef net_dvdplay_aem_DPEC_RESULT_INVALIDSLOT
#define net_dvdplay_aem_DPEC_RESULT_INVALIDSLOT 14L
#undef net_dvdplay_aem_DPEC_RESULT_INVALIDOP
#define net_dvdplay_aem_DPEC_RESULT_INVALIDOP 15L
#undef net_dvdplay_aem_DPEC_RESULT_WRONGMODE
#define net_dvdplay_aem_DPEC_RESULT_WRONGMODE 16L
#undef net_dvdplay_aem_DPEC_RESULT_WRONGSTATE
#define net_dvdplay_aem_DPEC_RESULT_WRONGSTATE 17L
#undef net_dvdplay_aem_DPEC_RESULT_WRONGMODEL
#define net_dvdplay_aem_DPEC_RESULT_WRONGMODEL 18L
#undef net_dvdplay_aem_DPEC_RESULT_CASEREJECTED
#define net_dvdplay_aem_DPEC_RESULT_CASEREJECTED 19L
#undef net_dvdplay_aem_DPEC_RESULT_CASEJAMMED
#define net_dvdplay_aem_DPEC_RESULT_CASEJAMMED 20L
#undef net_dvdplay_aem_DPEC_RESULT_CASERESEATED
#define net_dvdplay_aem_DPEC_RESULT_CASERESEATED 21L
#undef net_dvdplay_aem_DPEC_RESULT_CASEYANKEDOUT
#define net_dvdplay_aem_DPEC_RESULT_CASEYANKEDOUT 22L
#undef net_dvdplay_aem_DPEC_RESULT_CASESHOVEDIN
#define net_dvdplay_aem_DPEC_RESULT_CASESHOVEDIN 23L
#undef net_dvdplay_aem_DPEC_RESULT_CANTLOADDLL
#define net_dvdplay_aem_DPEC_RESULT_CANTLOADDLL 2001L
#undef net_dvdplay_aem_DPEC_RESULT_CANTFREEDLL
#define net_dvdplay_aem_DPEC_RESULT_CANTFREEDLL 2002L
#undef net_dvdplay_aem_DPEC_OPSTATE_UNKNOWN
#define net_dvdplay_aem_DPEC_OPSTATE_UNKNOWN 0L
#undef net_dvdplay_aem_DPEC_OPSTATE_QUEUED
#define net_dvdplay_aem_DPEC_OPSTATE_QUEUED 1L
#undef net_dvdplay_aem_DPEC_OPSTATE_PENDING
#define net_dvdplay_aem_DPEC_OPSTATE_PENDING 2L
#undef net_dvdplay_aem_DPEC_OPSTATE_INPROCESS
#define net_dvdplay_aem_DPEC_OPSTATE_INPROCESS 3L
#undef net_dvdplay_aem_DPEC_OPSTATE_COMPLETE
#define net_dvdplay_aem_DPEC_OPSTATE_COMPLETE 4L
#undef net_dvdplay_aem_DPEC_OPSTATE_RETIRED
#define net_dvdplay_aem_DPEC_OPSTATE_RETIRED 5L
#undef net_dvdplay_aem_DPEC_TAG_UNKNOWN
#define net_dvdplay_aem_DPEC_TAG_UNKNOWN 0L
#undef net_dvdplay_aem_DPEC_TAG_CNTRCAPLIST
#define net_dvdplay_aem_DPEC_TAG_CNTRCAPLIST 1L
#undef net_dvdplay_aem_DPEC_TAG_CNTRHWVERS
#define net_dvdplay_aem_DPEC_TAG_CNTRHWVERS 2L
#undef net_dvdplay_aem_DPEC_TAG_CNTRPLVERS
#define net_dvdplay_aem_DPEC_TAG_CNTRPLVERS 3L
#undef net_dvdplay_aem_DPEC_TAG_CNTRFWVERS
#define net_dvdplay_aem_DPEC_TAG_CNTRFWVERS 4L
#undef net_dvdplay_aem_DPEC_TAG_CNTRSERNUM
#define net_dvdplay_aem_DPEC_TAG_CNTRSERNUM 5L
#undef net_dvdplay_aem_DPEC_TAG_CNTRSTATUS
#define net_dvdplay_aem_DPEC_TAG_CNTRSTATUS 6L
#undef net_dvdplay_aem_DPEC_TAG_100P_TEMPFAN1
#define net_dvdplay_aem_DPEC_TAG_100P_TEMPFAN1 7L
#undef net_dvdplay_aem_DPEC_TAG_100P_TEMPFAN2
#define net_dvdplay_aem_DPEC_TAG_100P_TEMPFAN2 8L
#undef net_dvdplay_aem_DPEC_TAG_100P_TEMPFAN3
#define net_dvdplay_aem_DPEC_TAG_100P_TEMPFAN3 9L
#undef net_dvdplay_aem_DPEC_TAG_100P_TEMPFAN4
#define net_dvdplay_aem_DPEC_TAG_100P_TEMPFAN4 10L
#undef net_dvdplay_aem_DPEC_TAG_100P_POWER
#define net_dvdplay_aem_DPEC_TAG_100P_POWER 11L
#undef net_dvdplay_aem_DPEC_TAG_100P_SERVO
#define net_dvdplay_aem_DPEC_TAG_100P_SERVO 12L
#undef net_dvdplay_aem_DPEC_TAG_JRKERR_PARAMS
#define net_dvdplay_aem_DPEC_TAG_JRKERR_PARAMS 13L
#undef net_dvdplay_aem_DPEC_TAG_100P_DOOR
#define net_dvdplay_aem_DPEC_TAG_100P_DOOR 14L
#undef net_dvdplay_aem_DPEC_TAG_100P_ARM
#define net_dvdplay_aem_DPEC_TAG_100P_ARM 15L
#undef net_dvdplay_aem_DPEC_TAG_100P_ROLLER
#define net_dvdplay_aem_DPEC_TAG_100P_ROLLER 16L
#undef net_dvdplay_aem_DPEC_TAG_100P_MISCRBT
#define net_dvdplay_aem_DPEC_TAG_100P_MISCRBT 17L
#undef net_dvdplay_aem_DPEC_TAG_100P_LED
#define net_dvdplay_aem_DPEC_TAG_100P_LED 18L
/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    Connect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_DPEC_Connect
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    SetGlobalRef
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_DPEC_SetGlobalRef
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    ReleaseGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_DPEC_ReleaseGlobalRef
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    Disconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_DPEC_Disconnect
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    StartOperation
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_DPEC_StartOperation
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    GetOpState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_DPEC_GetOpState
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    AbortOperation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_DPEC_AbortOperation
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    RegForAsyncEvents
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_DPEC_RegForAsyncEvents
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    SetMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_DPEC_SetMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    GetMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_DPEC_GetMode
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    StartAppWatchdog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_DPEC_StartAppWatchdog
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    StrokeAppWatchdog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_DPEC_StrokeAppWatchdog
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    KillAppWatchdog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_DPEC_KillAppWatchdog
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    GetLibraryVersion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_DPEC_GetLibraryVersion
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    AddLineToLog
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_DPEC_AddLineToLog
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    StartLoggingService
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_DPEC_StartLoggingService
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_DPEC
 * Method:    KillLoggingService
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_DPEC_KillLoggingService
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
