/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_dvdplay_aem_BarCodeReader */

#ifndef _Included_net_dvdplay_aem_BarCodeReader
#define _Included_net_dvdplay_aem_BarCodeReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_dvdplay_aem_BarCodeReader
 * Method:    readBarCode
 * Signature: (Lnet/dvdplay/aem/BarCode;Ljava/lang/String;ZLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_dvdplay_aem_BarCodeReader_readBarCode
  (JNIEnv *, jclass, jobject, jstring, jboolean, jstring);

/*
 * Class:     net_dvdplay_aem_BarCodeReader
 * Method:    showVideoFormatDlg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_BarCodeReader_showVideoFormatDlg
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_BarCodeReader
 * Method:    showVideoSourceDlg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_BarCodeReader_showVideoSourceDlg
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_BarCodeReader
 * Method:    showVideoDisplayDlg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_BarCodeReader_showVideoDisplayDlg
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_BarCodeReader
 * Method:    showVideoCompressionDlg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_BarCodeReader_showVideoCompressionDlg
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_BarCodeReader
 * Method:    getVolume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_dvdplay_aem_BarCodeReader_getVolume
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_BarCodeReader
 * Method:    setVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_BarCodeReader_setVolume
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_dvdplay_aem_BarCodeReader
 * Method:    startButton
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_dvdplay_aem_BarCodeReader_startButton
  (JNIEnv *, jclass);

/*
 * Class:     net_dvdplay_aem_BarCodeReader
 * Method:    checkInstance
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_dvdplay_aem_BarCodeReader_checkInstance
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
